### login
POST http://localhost:8000/todoapps/api/v1/user/login
Content-Type: application/json

{
    "email": "kaizer@gmail.com",
    "password": "sekolahan"
}
###
GET http://localhost:8000/todoapps/api/v1/user

### add
POST http://localhost:8000/todoapps/api/v1/user/
Content-Type: application/json

{
    "name": "kaizer",
    "email": "kaizer@gmail.com",
    "password": "sekolahan"
}

### update
PUT http://localhost:8000/todoapps/api/v1/user/66b97e3c4ebd031df4052feb
Content-Type: application/json

{
    "name": "kaizer r3",
    "email": "kaizer@gmail.com",
    "password": "sekolahan"
}

### delete
DELETE http://localhost:8000/todoapps/api/v1/user/66b8a0107ae867ea8993667a
